### ISSUE TITLE
Company Data Unretrievable

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#1]
Company data from the main server cannot be retrieved due to a 401 (Unauthorized) error. This makes the entire visitor card transaction impossible to complete. The error leads me to the VisitorController class, as the Json cannot be created because of this.

**Comment by ghost** [comment]
Made commit, which should fix this problem. Whole visitor transaction should work now. Can't test didn't had time to fully fix mainServer.

**Comment by chellerific** [comment]
The problem hasn't been fixed as there are issues regarding SSL connection in the tables related with Visitors.

**Comment by ghost** [comment]
Company data is now retrievable.
