### ISSUE TITLE
Employee design

### ISSUE THREAD

**Issue by Maievmau** [ActiveAgeingHKR/JavaFXunit#11]
Not a bug, just a design "issue". When i go to create a new employee, the fields are missaligned with the text:
![employee](https://cloud.githubusercontent.com/assets/17614378/21644461/d91a39da-d28d-11e6-959e-8122610687d8.PNG)

**Comment by chellerific** [comment]
I am unsure about this one because this problem does not occur for me.

**Comment by SE-Design** [comment]
Design issue in Employee.
![capture003](https://cloud.githubusercontent.com/assets/18417398/21713243/39967d66-d3f9-11e6-8056-12a5564d5912.JPG)

**Comment by chellerific** [comment]
It's normal for me:
![normal](https://cloud.githubusercontent.com/assets/11857430/21717769/7325c702-d413-11e6-8335-f105a2c1d35e.png)
