### ISSUE TITLE
Remove Customer function is not working

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#12]
The button for removing customers on the database is not working at all. Tested it if the function works after signing out and signing back in but no customer is getting removed with the press of the button.

**Comment by chellerific** [comment]
The bug unfortunately still exists.

**Comment by surajbaral** [comment]
Still?? I will take a look and come back

**Comment by surajbaral** [comment]
I have asked Iiliu for help, he had pushed new code. That should solve the problem.

**Comment by chellerific** [comment]
When I check the console while clicking "remove", no request method is being invoked at all / nothing shows up.
