### ISSUE TITLE
Editing Customer's Medicine not working

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#13]
Under the Customer's Medicine tab, it is impossible to edit the Start Date and Frequency fields for an existing customer's medicine info. Also impossible to remove a row.

**Comment by Wogii** [comment]
fixed problem nbr #13 nee to ad update function for the table to show new values
commit nbr: 005757f4d57970936dda2d2acfc5fc46539b5f3c
