### ISSUE TITLE
Customer Creation Unclear for the Admin

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#3]
When an admin tries to register a new customer, the customer cannot be listed immediately in the table. It creates an error when you try to register one. However, the new customer only shows up when the admin signs out and signs back in again. The registration is being done but presents this difficulty.

**Comment by lukashkatman** [comment]
Hi, now the customer table should be refreshed after registering a new customer. Because of not being able to run server (problem on deploying main server), I haven't got chance to see the result. But I am hoping, with my latest commit the problem of refreshing table should have been fixed.
