### ISSUE TITLE
Devices Cannot Be Binded to Customers

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#4]
The admin is not able to bind devices to customers as customers cannot be retrieved in the drop down. The error is a JsonException and has to do with the syntax.

**Comment by Bitharis** [comment]
Hello guys I got an email that I was assigned to this problem. Is there anthing you want me to check from the server side?

**Comment by chellerific** [comment]
Don't worry Panos it was a mistake
