### ISSUE TITLE
Device Registration Unclear 

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#5]
The admin GUI has a button for Devices, however it seems that this page is mainly for binding devices to customers. How do we know about the registered devices? There are only two fields for devices but it is unclear if they are for creation or selecting a device that will be binded to the customer.

**Comment by lukashkatman** [comment]
Yes, it is designed in a way that all new devices will be registered and directly get assigned to customer. We are following  the principle that a device will be saved to system only if it has the user for it.
