### ISSUE TITLE
Admin LogIn Not Working

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#9]
From the pull of the latest version logging in is no longer working. Exceptions seem to lead to errors in loading FXMLs properly.

**Comment by chellerific** [comment]
"LOAD PAGE EXCEPTION: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher"

I got this error when I tried using my own credentials that I made. Which input is it referring to?

**Comment by chellerific** [comment]
With Panos' suggestions I have done the following inside the Managers table:

- Replaced password in database with MhebVST2TYZ3OaOkD/QIvA==
- Replaced username in database with JackBlack
- Logged into the gui using credentials JackBlack and password1 

However I get a new SSL error:

LOAD PAGE EXCEPTION: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by swashyson** [comment]
Fixed with panos SSLConnector class
